In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.3.1+cu121


## Intro to Tensors
### Creating a Tensor

Pytorch tensors are created using 'torch.Tensor()'

In [3]:
# scalar
scalar = torch.tensor(7)
print(scalar)

print(scalar.ndim) # scalar dimension
print(scalar.item()) # get tensor back as python integer

tensor(7)
0
7


In [4]:
# Vector
vector = torch.tensor([7,7])
print(vector)

vector.ndim

vector.shape # size of vector matrix

tensor([7, 7])


torch.Size([2])

In [5]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
print(MATRIX.ndim)
print(MATRIX[1]) # index first array, or column
print(MATRIX.shape) # indicating a 2x2 matrix

2
tensor([ 9, 10])
torch.Size([2, 2])


In [6]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
print(TENSOR)
print(TENSOR.ndim)
print(TENSOR.shape)
print(TENSOR[0])

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])
3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])


### Random Tensors

Why random tensors? 

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'Start with random nymbers -> look at data -> update random numbers -> look at data -> update random numbers'

In [7]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
print(random_tensor)
print(random_tensor.ndim)

tensor([[0.5882, 0.8090, 0.1367, 0.6002],
        [0.6218, 0.2989, 0.1833, 0.8848],
        [0.7669, 0.8181, 0.1800, 0.3777]])
2


In [8]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, and color channels (RGB)
print(random_image_size_tensor.shape, random_image_size_tensor.ndim)

torch.Size([224, 224, 3]) 3


### Zeros and Ones

In [9]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
print(zeros)

# Create a tensor of all ones
ones = torch.ones(size=(3,4))
print(ones)
print(ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32


### Creating a range of tensors and tensors-like

In [10]:
# Use torch.range()
one_to_ten = torch.arange(start=0, end=1000, step=77)
print(one_to_ten)

# Creating tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
print(ten_zeros)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


### Tensor Data Types

Data types have to do with computer science precision. Which, as I am understanding is the degree of accuracey and resource usage of memory. So storing something with 32 bit accuracey vs 16 bit accuracey in memory. 

**Note:** tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right Datatype
2. Tensors not right Shape
3. Tensors not on the right device

In [11]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], 
                              dtype=None, # what datatype is the tensor
                              device=None, # use GPU or CPU
                              requires_grad=False) # are we backpropagating with the gradiant?
print(float_32_tensor)
print(float_32_tensor.dtype)

float_16_tensor = float_32_tensor.type(torch.float16)
print(float_16_tensor.type())

tensor([3., 6., 9.])
torch.float32
torch.HalfTensor


### Tensor Mainpulation:
1. Addition
2. Subtraction
3. Multpilication
4. Division
5. Matrix Multiplication

In [12]:
tensor = torch.tensor([1, 2, 3])

# Addition
tensor_plus = tensor + tensor
print(tensor_plus)

# Multiplication
tensor_times = tensor * tensor
print(tensor_times)

# PyTorch Built In
tensor_py = torch.mul(tensor, tensor)
print(tensor_py)

# Matrix Multiplication
tensor_matmul = torch.matmul(tensor, tensor)
print(tensor_matmul)

# MatMul as a for loop
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor([2, 4, 6])
tensor([1, 4, 9])
tensor([1, 4, 9])
tensor(14)
tensor(14)


In [13]:
# The Transpose!
rand_tensor = torch.rand(3,4)
rand_tensor_trans = rand_tensor.mT
print(rand_tensor, rand_tensor.shape)
print(rand_tensor_trans, rand_tensor_trans.shape)

tensor([[0.5710, 0.4201, 0.5726, 0.2039],
        [0.4611, 0.0423, 0.2395, 0.7464],
        [0.4894, 0.1080, 0.7210, 0.2331]]) torch.Size([3, 4])
tensor([[0.5710, 0.4611, 0.4894],
        [0.4201, 0.0423, 0.1080],
        [0.5726, 0.2395, 0.7210],
        [0.2039, 0.7464, 0.2331]]) torch.Size([4, 3])


### Tensor Aggregation

Min, max, mean, sum, etc.

In [14]:
# Create a tensor

x = torch.arange(0, 100, 10)
print(x, x.dtype)

print(torch.min(x), x.min())

print(torch.max(x), x.max())

print(torch.mean(x.type(torch.float32)), x.type(torch.float32).mean())

print(torch.sum(x), x.sum())

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]) torch.int64
tensor(0) tensor(0)
tensor(90) tensor(90)
tensor(45.) tensor(45.)
tensor(450) tensor(450)


### Positionals

In [15]:
print(x)

print(x.argmin(), x.argmax()) # returns index position of min and max

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])
tensor(0) tensor(9)


### Reshaping, Stacking, Squeezing, and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape.
* View - return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all '1' dimensions for a tensor
* Unsqueeze - adds a '1' dimension to a target tensor
* Premute - return a view of the inpte iwith dimensions permuted (swapped) in a certain way

In [16]:
# Create a tensor
a = torch.arange(1.0, 11.0)
print(a, a.shape)

# Add an extra dimension
a_reshaped = a.reshape(2, 5) # can do it with multiples of 10 (1, 10), (10, 1), (5, 2), (2, 5)
print(a_reshaped, a_reshaped.shape)

# Change the view, this thing is useless as far as I understand
b = a.view(1,10)
print(b, b.shape)

# Stacking
a_stacked = torch.stack([a, a, a, a], dim=1) # can change dim between 0,1
print(a_stacked)

# Squeezing
a_squeezed = torch.squeeze(a)
print(a_squeezed, a_squeezed.shape)

a_unsqueeze = torch.unsqueeze(a, dim=0)
print(a_unsqueeze, a_unsqueeze.shape)

# Permuting
a_permute = torch.permute(a_unsqueeze, dims=(1,0))
print(a_permute, a_permute.shape)

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) torch.Size([10])
tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.]]) torch.Size([2, 5])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([1, 10])
tensor([[ 1.,  1.,  1.,  1.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])
tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]) torch.Size([10])
tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]) torch.Size([1, 10])
tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]]) torch.Size([10, 1])


### Indexing

Very similar to Numpy, or pandas

In [29]:
c = torch.arange(1, 11).reshape(1, 2, 5)
print(c, c.shape)

print(c[0]) # index first dim
print(c[0][0]) # Index on middle bracket (dim=1)
print(c[0][1][3]) # play around
print(c[:, 0]) # pandas rules

tensor([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10]]]) torch.Size([1, 2, 5])
tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])
tensor([1, 2, 3, 4, 5])
tensor(9)
tensor([[1, 2, 3, 4, 5]])


### PyTorch tensors & NumPy

Required by PT on install. We may need to understand how they communicate.

torch.form_numpy(ndarray)
torch.Tensor.numpy()

In [33]:
import numpy as np

# Numpy array to Tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
print(array, "  ", tensor)

array = array + 1
print(array, "  ", tensor)

[1. 2. 3. 4. 5. 6. 7.]    tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
[2. 3. 4. 5. 6. 7. 8.]    tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)


In [35]:
# Tensor to Numpy Array

tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
print(tensor, "   ", numpy_tensor)

tensor = tensor + 1
print(tensor, "   ", numpy_tensor)

tensor([1., 1., 1., 1., 1., 1., 1.])     [1. 1. 1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2., 2., 2.])     [1. 1. 1. 1. 1. 1. 1.]


### Reproducibility

In short, how a neural network learns:
1. Start with random numbers.
2. Perform Tensor operations.
3. Update random numbers with better accuracy.
4. Repeat 1-3 like 100000 times.

**random seed** - essentially "flavors" the randomness

In [38]:
# Create two random tensors
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A, "\n", random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.6988, 0.8029, 0.3417, 0.0149],
        [0.5169, 0.1188, 0.3119, 0.9470],
        [0.8079, 0.7603, 0.6695, 0.7932]]) 
 tensor([[0.1877, 0.9744, 0.9888, 0.1899],
        [0.1122, 0.9408, 0.3838, 0.6853],
        [0.4124, 0.6373, 0.9466, 0.1461]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [41]:
# random, but reproducable tensors
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C, "\n", random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]]) 
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [44]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else False

tensor = torch.tensor([1, 2, 3])
print(tensor, tensor.device)

# How to move tensor
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')